import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { ModalProvider } from "@/components/ModalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <Navbar />
          <ModalProvider>
          <div className="mt-8 w-[91%] mx-auto">{children}</div>
          </ModalProvider>
        </div>
      </body>
    </html>
  );
}
